[device-mac-randomization]
wifi.scan-rand-mac-address = yes

[connection-wifi]
wifi.cloned-mac-address = random

[connection-ethernet]
ethernet.cloned-mac-address = permanent

[device-wifi]
wifi.scan-rand-mac-address = yes
