[Appearance]
style = kvantum
icon_theme = Papirus-Dark
standard_dialogs = xdgdesktopportal

[Fonts]
fixed = "Iosevka,14,-1,5,50,0,0,0,0,0"
general = "Iosevka Aile,14,-1,5,50,0,0,0,0,0"

[Interface]
activate_item_on_single_click = 1
