name: Generate ISO

on:
  workflow_run:
    workflows: ["Build Image"]
    branches: ["main", "system"]
    types:
      - completed
  workflow_dispatch: # allow manually triggering builds

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  titanoboa:
    name: Generate Installer ISO
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Maximize Build Space
        uses: ublue-os/remove-unwanted-software@v9

      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Mount BTRFS for podman storage
        id: container-storage-action
        uses: ublue-os/container-storage-action@911baca08baf30c8654933e9e9723cb399892140
        continue-on-error: true
        with:
          target-dir: /var/lib/containers
          mount-opts: compress-force=zstd:2

      - name: Generate ISO
        id: generate
        uses: osbuild/bootc-image-builder-action@main
        with:
          builder-image: ghcr.io/victorvintorez/bootc-image-builder:latest
          config-file: ./files/installer/config.toml
          image: ghcr.io/${{ github.repository }}-installer:br-system-43
          types: anaconda-iso
          rootfs: btrfs
          additional-args: --use-librepo

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iso
          path: ${{ steps.generate.outputs.output-directory }}
          if-no-files-found: error
